# Generated by Django 4.2 on 2023-05-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_alter_pessoa_cpf_alter_pessoa_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(),
        ),
    ]
